// <auto-generated />
namespace POS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Modified_JoiningDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modified_JoiningDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201806020728378_Modified_JoiningDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
