// <auto-generated />
namespace POS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ForeignKey_added_To_Employee1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForeignKey_added_To_Employee1));
        
        string IMigrationMetadata.Id
        {
            get { return "201806040622200_ForeignKey_added_To_Employee1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
