// <auto-generated />
namespace POS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Employeee_model_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employeee_model_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201806011815128_Employeee_model_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
