// <auto-generated />
namespace POS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Total_Price_added_to_purchaseDetailes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Total_Price_added_to_purchaseDetailes));
        
        string IMigrationMetadata.Id
        {
            get { return "201806042212355_Total_Price_added_to_purchaseDetailes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
